/*
Machinery Class: it is also POJO class which accept Products and return products details it contain following methods 

Machinery class contain field id, name, comp, capacity 

Note: machinery cannot accept product count more than its capacity of products 

void setProducts(Product p[]): this function can accept number of products for products 

Product [] getProducts(): this function can return total number product machinery class

int getTotalProductsCount(): this function can return total products count generated by machines  

Product getProductById(int id): this function can accept id of product generated by machine and return product reference and if product not found return null
*/

class Machinery
{
	private int id;
	private String name;
	private String comp;
	private int capacity;
	private Product[] p;
	private int productCount;
	private Scanner sc;

	public void setProduct(int ...p)
	{
		this.p=p;
	}
	public product[] getProducts()
	{
		return product[];
	} 

	public int getTotalProductsCount()
	{
		return p.length;
	}

	public product getProductById(int id)
	{
		for(int i=0;i<p.length;i++)
		{
			if(p[i].getId()==id)
			{
				return p[i];
			}
		}

		return null;
	}

	public void setId(int id)
	{
		this.id=id;
	}
	public int getId()
	{
		return id;
	}

	public void setName(String name)
	{
		this.name=name;
	}
	public String getName()
	{
		return name;
	}

	public void setComp(String comp)
	{
		this.comp=comp;
	}
	public String getComp()
	{
		return comp;
	}

	public void setCapacity(int capacity)
	{
		this.capacity=capacity;
	}
	public int getCapacity()
	{
		return capacity;	
	}


	public void productApp(Scanner sc)
	{
		this.sc=sc;
		System.out.println("Enter Total Number of Products made by this machine ");
		int num=sc.nextInt();
		Product[] p=new Product[num];
		for(int i=0;i<p.length;i++)
		{
			p[i]=new Product();
			System.out.println("Enter Product Id ");
			int id=sc.nextInt();
			p[i].setId(id);
			sc.nextLine();

			System.out.println("Enter Product Name ");
			String name=sc.nextLine();
			p[i].setName(name);

			System.out.println("Enter Product rate ");
			float rate=sc.nextFloat();
			p[i].setRate(rate);

			System.out.println("Enter Product Quality ");
			float qty=sc.nextFloat();
			p[i].setQty(qty);

			System.out.println("Enter Product Count ");
			int count=sc.nextInt();
			p[i].setCount();
		}
		
		
	}
}