/*
Q1. Suppose consider we are working on Manufacturing company production house and we have some machinery 
in production house can produce some product and we want develop the application for following purpose 

1.Allocate machinery for production house
2.Allocate products to machinery 
3.Count the total number of products produced by all machines
4.Count the all products produced by single specific machine by using its id
5.View all products from production house
6.View all products produced by particular machine

For achieve about task we have following class structure 
1.Product class : it is POJO class with field id,name,rate,qty,count
2.Machinery Class: it is also POJO class which accept Products and return products details it contain following methods 
	Machinery class contain field id, name, comp, capacity
 
	Note: machinery cannot accept product count more than its capacity of products 

	void setProducts(Product p[]): this function can accept number of products for products 

	Product [] getProducts(): this function can return total number product machinery class

	int getTotalProductsCount(): this function can return total products count generated by machines  

	Product getProductById(int id): this function can accept id of product generated by machine and return product reference and if product not found return null

3.ProductionHouse : this class can accept Machinery and machine class have some details Machinery class contain field id, name, comp, capacity 
	Note: machinery cannot accept product count more than its capacity of products 

	ProductionHouse class contain following methods 
	void allocateMachine(Machinery m[]): this method can accept multiple machinery
	Machinery [] getMachinery(): this method can return all machineries with details 
	Product [] getProductsByMachineryId(int id): this function can accept machinery id and return all products produced by machine and if id not found return null
	Machinery [] getAllProductionByAllMachine(): this method can return all machinery and its product details 

4.ManufacturingHub : this is the main method class and this class contain cases for perform above operation

*/

import java.util.Scanner;
class ManufacturingHub
{
	Scanner sc=new Scanner(System.in);

	public void setProductionHouse()
	{
		System.out.println("Enter Total Number of Production House");
		int h=sc.nextInt();

		
		ProductionHouse[] pHouse=new ProductionHouse[h];
		
		for(int i=0;i<pHouse.length;i++)
		{
			pHouse[i]=new ProductionHouse();
			
			System.out.println("Enter ProductionHouse id");
			int id=sc.nextInt();
			pHouse[i].setId(id);
			sc.nextLine();
			
			System.out.println("Enter ProductionHouse Name");
			String name=sc.nextLine();
			pHouse[i].setName(name);
			
			System.out.println("Enter ProductionHouse Company Name");
			String comp=sc.nextLine();
			pHouse[i].setComp(comp);
			
			System.out.println("ProductionHouse Capacity is "+h);
			pHouse[i].setCapacity(h);'
		}
	
		
	}
	public static void main(String[] args)
	{
		
		ManufacturingHub mHub=new ManufacturingHub();
		mHub.setProductionHouse();
		
	}
}




















